### ISSUE TITLE
Hamiltonian Cycle gen

### ISSUE THREAD

**Issue by TheWalkingSea** [taaha-khan/snake-game-algorithm#2]
So I have been reading your code for quite a while and I have come to a stop. Where you pass the prim alg to process a hamiltonian cycle just doesnt make sense to me. I have come to ask for a more detailed version of what it really does and how in the world it works

**Comment by taaha-khan** [comment]
@TheWalkingSea I think you are talking about [this section](https://github.com/taaha-khan/snake-game-algorithm/blob/7776bfa5e331e6b2e88db2a492cede675ca3693d/SnakeGameAlgorithm/Hamilton%20New/cycle.py#L64) where the Prim tree has already been generated, and we are using it to generate the hamiltonian cycle. I apologize, I didn't really write this code with readability in mind. 

Basically, we are using the Prim tree as a maze in the grid. 

<img width="911" alt="prim_grid" src="https://user-images.githubusercontent.com/61217792/138567163-aba43b5e-e9db-4ca7-906a-cc16aaf9c1cd.png"> Here it shows the blue dots as walls in the maze and the grey dots as positions in the grid. Notice how the Prim tree is half the resolution of the actual grid, giving 2 grid dots between the walls.

We start the "Runner" at a random position in the grid. It will then treat the Prim tree as walls in a maze and will move through the grid given some conditions. It will always turn left if it is available and not blocked by the Prim maze, otherwise it will move straight if available, and lastly it will turn right if that is the only move. This is operating under the concept that you can always exit (most) mazes if you keep your hand on one wall, and never let go, because you will go down every corridor at least once and find the exit. For this usage, we are just trying to move down every corridor and end up back to where we started, making a random cycle through the grid. 


(To clarify, this image and the one above are two different Prim generations)
<img width="910" alt="hcycle_prim" src="https://user-images.githubusercontent.com/61217792/138567278-266b0396-edef-4472-adf9-0d2f53ec521b.png">

If you have the code downloaded, you can add the line `self.hc.show(animating = True)` to line 151 right before the main run loop in `main.py`. This will animate the generation of Prim and the Hamiltonian Cycle before running the simulation.

Most of the concept of this is taken from [John Tapsell](https://johnflux.com/2015/05/02/nokia-6110-part-3-algorithms/) who initially wrote the algorithm for this. Let me know if you have any more questions.
